/* Create Tables */

CREATE TABLE ACCOUNT
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	FIRST_NAME VARCHAR(64) NOT NULL,
	LAST_NAME VARCHAR(64),
	PHONE_NUMBER VARCHAR(24) NOT NULL,
	EMAIL VARCHAR(128) NOT NULL,
	PASSWORD VARCHAR(256) NOT NULL,
	VERIFIED TINYINT,
	ACCOUNT_TYPE_ID SMALLINT NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE ACCOUNT_TYPE
(
	ID SMALLINT NOT NULL AUTO_INCREMENT,
	VALUE VARCHAR(64) NOT NULL UNIQUE,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE FRIEND
(
	ID BIGINT(0) NOT NULL AUTO_INCREMENT,
	FIRSTNAME VARCHAR(64),
	LASTNAME VARCHAR(64),
	FACEBOOK_ID BIGINT(0),
	USERNAME VARCHAR(64),
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE KIKBAK
(
	ID BIGINT NOT NULL UNIQUE AUTO_INCREMENT,
	MERCHANT_ID BIGINT NOT NULL,
	LOCATION_ID BIGINT NOT NULL,
	USER_ID BIGINT NOT NULL,
	REWARD_ID BIGINT NOT NULL,
	MULTIPLIER_ID BIGINT NOT NULL,
	START_DATE DATETIME NOT NULL,
	EXPIRATION_DATE DATETIME NOT NULL,
	REDEEMED_DATE DATETIME,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE KIKBAKUSER
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	FIRSTNAME VARCHAR(64),
	LASTNAME VARCHAR(64),
	EMAIL VARCHAR(128),
	FACEBOOK_ID BIGINT(0),
	GENDER TINYINT,
	CREATE_DATE DATETIME NOT NULL,
	UPDATE_DATE DATETIME,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE KIKBAKUSER2FRIEND
(
	USER_ID BIGINT NOT NULL,
	FRIEND_ID BIGINT(0) NOT NULL,
	FACEBOOK_FRIEND_ID BIGINT NOT NULL
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE LOCATION
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	KIKBAK_VERIFICATION_CODE VARCHAR(8) NOT NULL,
	ADDRESS_1 VARCHAR(256) NOT NULL,
	ADDRESS_2 VARCHAR(256),
	CITY VARCHAR(128) NOT NULL,
	STATE VARCHAR(24) NOT NULL,
	ZIPCODE INT NOT NULL,
	ZIP_PLUS_FOUR VARCHAR(4),
	MERCHANT_ID BIGINT NOT NULL,
	LATITUDE DOUBLE NOT NULL,
	LONGITUDE DOUBLE NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE MERCHANT
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(64) NOT NULL,
	MERCHANT_TYPE BIGINT(0) NOT NULL,
	DESCRIPTION VARCHAR(1024),
	GRAPH_PATH VARCHAR(512) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE REWARD
(
	ID BIGINT NOT NULL UNIQUE AUTO_INCREMENT,
	MERCHANT_ID BIGINT NOT NULL,
	LOCATION_ID BIGINT NOT NULL,
	NAME VARCHAR(64) NOT NULL,
	DESCRIPTION VARCHAR(4096) NOT NULL,
	SHARER_VALUE DOUBLE NOT NULL,
	SHAREE_VALUE DOUBLE NOT NULL,
	REWARD_TYPE INT NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE REWARDMULTIPLIER
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	MULTIPLIER DOUBLE,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE SHARING
(
	ID BIGINT NOT NULL UNIQUE AUTO_INCREMENT,
	FACEBOOK_ID BIGINT NOT NULL UNIQUE,
	LOCATION_ID BIGINT NOT NULL,
	GRAPH_PATH VARCHAR(512) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;



/* Create Indexes */

CREATE INDEX EMAIL_KEY ON ACCOUNT (EMAIL ASC);
CREATE INDEX EMAIL_PASSWORD_KEY ON ACCOUNT (EMAIL ASC, PASSWORD ASC);
CREATE INDEX FACEBOOK_ID_KEY USING BTREE ON FRIEND (FACEBOOK_ID ASC);
CREATE INDEX DATE_RANGE_KEY USING BTREE ON KIKBAK (START_DATE ASC, EXPIRATION_DATE ASC);
CREATE INDEX REDEEMED_DATE_KEY ON KIKBAK (REDEEMED_DATE ASC);
CREATE INDEX MERCHANT_ID_LEY ON KIKBAK (MERCHANT_ID ASC);
CREATE INDEX LOCATION_ID_KEY ON KIKBAK (LOCATION_ID ASC);
CREATE INDEX USER_ID_KEY ON KIKBAK (USER_ID ASC);
CREATE INDEX FACEBOOK_ID_KE USING BTREE ON KIKBAKUSER (FACEBOOK_ID ASC);
CREATE INDEX EMAIL_KEY USING BTREE ON KIKBAKUSER (EMAIL ASC);
CREATE INDEX CREATE_DATE_KEY ON KIKBAKUSER (CREATE_DATE ASC);
CREATE INDEX GENDER_KEY ON KIKBAKUSER (GENDER ASC);
CREATE INDEX USER_ID_KEY USING BTREE ON KIKBAKUSER2FRIEND (USER_ID ASC, FACEBOOK_FRIEND_ID ASC);
CREATE INDEX MERCHANT_ID_KEY ON LOCATION (MERCHANT_ID ASC);
CREATE INDEX GEO_KEY ON LOCATION (LATITUDE ASC, LONGITUDE ASC);
CREATE INDEX ZIPCODE_KEY ON LOCATION (ZIPCODE ASC);
CREATE INDEX NAME_KEY USING BTREE ON MERCHANT (NAME ASC);
CREATE INDEX MERCHANT_TYPE_KEY USING BTREE ON MERCHANT (MERCHANT_TYPE ASC);
CREATE INDEX MERCHANT_ID_KEY USING BTREE ON REWARD (MERCHANT_ID ASC);
CREATE INDEX LOCATION_ID_KEY ON REWARD (LOCATION_ID ASC);
CREATE INDEX REWARD_TYPE_KEY ON REWARD (REWARD_TYPE ASC);
CREATE INDEX FACEBOOK_ID_KEY USING BTREE ON SHARING (FACEBOOK_ID ASC);
CREATE INDEX LOCATION_ID_KEY USING BTREE ON SHARING (LOCATION_ID ASC);



